"""initial migration

Revision ID: 8d876c04f2b4
Revises: b0528adfbe53
Create Date: 2017-11-22 15:00:54.802000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d876c04f2b4'
down_revision = 'b0528adfbe53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tuijian', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('tuijiantime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_tuijiantime'), 'posts', ['tuijiantime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tuijiantime'), table_name='posts')
    op.drop_column('posts', 'tuijiantime')
    op.drop_column('posts', 'tuijian')
    # ### end Alembic commands ###
